[window]
decorations = "Full"
# startup_mode = "Fullscreen"
startup_mode = "Maximized"
dynamic_title = false
padding = { x = 2, y = 0 }

[general]
live_config_reload = true

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Retina" }
bold   = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
size = 15

[bell]
command = "None"

[cursor] 
style.shape = "Block"
style.blinking = "Never"
unfocused_hollow = true

[terminal]
shell = "ubuntu"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "n", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
    { key = "=", mods = "Control",       action = "ResetFontSize" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "+", mods = "Control", action = "None" },
    { key = "-", mods = "Control", action = "None" },
    { key = "F11", action = "ToggleFullscreen" },
    { key="Key0", mods= "Control", chars= "\u001b[48;5u" },
    { key="Key1", mods= "Control", chars= "\u001b[49;5u" },
    { key="Key2", mods= "Control", chars= "\u001b[50;5u" },
    { key="Key3", mods= "Control", chars= "\u001b[51;5u" },
    { key="Key4", mods= "Control", chars= "\u001b[52;5u" },
    { key="Key5", mods= "Control", chars= "\u001b[53;5u" },
    { key="Key6", mods= "Control", chars= "\u001b[54;5u" },
    { key="Key7", mods= "Control", chars= "\u001b[55;5u" },
    { key="Key8", mods= "Control", chars= "\u001b[56;5u" },
    { key="Key9", mods= "Control", chars= "\u001b[57;5u" }
]

[colors.primary]
background = '#0E1415'
foreground = '#CECECE'

[colors.cursor]
text = '#0E1415'
cursor = '#CECECE'

[colors.normal]
black = '#0E1415'
red = '#e25d56'
green = '#73ca50'
yellow = '#e9bf57'
blue = '#4a88e4'
magenta = '#915caf'
cyan = '#23acdd'
white = '#f0f0f0'

[colors.bright]
black = '#777777'
red = '#f36868'
green = '#88db3f'
yellow = '#f0bf7a'
blue = '#6f8fdb'
magenta = '#e987e9'
cyan = '#4ac9e2'
white = '#FFFFFF'
